### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by gabrielzschmitz** [Andrmist/dwm-polybar#2]
Can you please make a way to easily change the colors of the output without the need of sed?
The way I'm doing right now:
```sh
dwm-polybar --monitor 0 | sed 's/%{B#005577}/%{B#COLOR}/g'
```

**Comment by Andrmist** [comment]
I can add environment variables or config file

**Comment by gabrielzschmitz** [comment]
Sure, that would be awesome, to select colors for the active background and foreground and for the inative too.

**Comment by Andrmist** [comment]
Added: [7485d1a](https://github.com/Andrmist/dwm-polybar/commit/7485d1a63c3e8a5fd059caeda1006d70d391577c)

Env variables don't work for now unfortunately, i'll fix it in next commits

**Comment by gabrielzschmitz** [comment]
This was already a big step forward, thank you!
